### ISSUE TITLE
RuntimeException: Could not load script: 

### ISSUE THREAD

**Issue by anand853** [galenframework/galen-sample-tests#2]
when a run the script im getting below error.kindly help me on this

C:\galenframework\sample\galen-sample-tests-master>galen.bat test tests/ --htmlreport reports
Exception in thread "main" java.lang.RuntimeException: Could not load script: C:\galenframework\sample\galen-sample-tests-master\tests\pages/LoginPage.js
        at net.mindengine.galen.javascript.JsFunctionLoad.load(JsFunctionLoad.java:110)
        at net.mindengine.galen.javascript.JsFunctionLoad.call(JsFunctionLoad.java:58)
        at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)

**Comment by ishubin** [comment]
Seems like again a problem with understanding the file separators in Windows. Unfortunately I don't have Windows machine to reproduce it.
